version: '3'

services:
  mysql:
    image: mysql:5.7.23
    volumes:
      - ../data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
      MYSQL_PASSWORD: django_password
      MYSQL_USER: django
    ports:
      - "3306:3306"
  graph:
    container_name: neo4j
    image: neo4j:3.5
    ports:
      # Comment these two out in produciton
      - "7474:7474"
      - "7687:7687"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - ../data/neo4j/data:/data
      - ../data/neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=4G
  web:
    container_name: web_dock
    image: xchem/fragalysis-stack:latest
    command: /bin/bash /code/launch-stack.sh
    volumes:
      - ../data/logs:/code/logs/
      - ../data/media:/code/media/
      - ../fragalysis-frontend:/code/frontend
      - ../fragalysis-backend:/code/
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - graph
  loader:
    container_name: loader
    image: loader:latest
    volumes:
      - ../data/input:/fragalysis
      - ../data/media:/code/media
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
      MYSQL_PASSWORD: django_password
      MYSQL_USER: django
      DATA_ORIGIN: EXAMPLE
    depends_on:
      - mysql
